# Generated by Django 5.1.2 on 2025-11-22 21:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_entity_type', models.CharField(choices=[('asset', 'Asset'), ('identity', 'Identity'), ('group', 'Group'), ('environment', 'Environment'), ('location', 'Location'), ('team', 'Team'), ('business_service', 'Business Service')], max_length=64)),
                ('from_entity_id', models.UUIDField()),
                ('to_entity_type', models.CharField(choices=[('asset', 'Asset'), ('identity', 'Identity'), ('group', 'Group'), ('environment', 'Environment'), ('location', 'Location'), ('team', 'Team'), ('business_service', 'Business Service')], max_length=64)),
                ('to_entity_id', models.UUIDField()),
                ('relationship_type', models.CharField(choices=[('runs_in', 'Runs in'), ('hosted_in', 'Hosted in'), ('depends_on', 'Depends on'), ('connected_to', 'Connected to'), ('backs_up', 'Backs up'), ('parent_of', 'Parent of'), ('located_at', 'Located at'), ('owns', 'Owns'), ('uses', 'Uses'), ('admin_of', 'Admin of'), ('has_access_to', 'Has access to'), ('member_of', 'Member of'), ('manages', 'Manages'), ('assumes_role', 'Assumes role'), ('other', 'Other')], max_length=64)),
                ('source', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=64)),
                ('confidence', models.FloatField(default=1.0)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['from_entity_type', 'from_entity_id'], name='intelligenc_from_en_77cc8c_idx'), models.Index(fields=['to_entity_type', 'to_entity_id'], name='intelligenc_to_enti_3191c0_idx'), models.Index(fields=['relationship_type'], name='intelligenc_relatio_f1e076_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalID',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('asset', 'Asset'), ('identity', 'Identity'), ('group', 'Group'), ('environment', 'Environment'), ('location', 'Location'), ('team', 'Team'), ('business_service', 'Business Service')], max_length=64)),
                ('entity_uuid', models.UUIDField()),
                ('source', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], max_length=64)),
                ('external_id', models.CharField(max_length=256)),
                ('external_id_type', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_uuid'], name='intelligenc_entity__b483ba_idx'), models.Index(fields=['source', 'external_id'], name='intelligenc_source_73c574_idx')],
                'unique_together': {('entity_type', 'entity_uuid', 'source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('criticality', models.CharField(choices=[('tier0', 'Tier 0'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_teams', to='intelligence.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('office', 'Office'), ('datacenter', 'Data Center'), ('cloud_region', 'Cloud Region'), ('other', 'Other')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state_region', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('tier', models.CharField(choices=[('tier0', 'Tier 0'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('lifecycle_state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('stale', 'Stale')], default='active', max_length=32)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='intelligence.team')),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('human', 'Human'), ('service', 'Service Account'), ('privileged', 'Privileged'), ('shared', 'Shared'), ('break_glass', 'Break-glass')], default='human', max_length=32)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('org_unit', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending'), ('terminated', 'Terminated'), ('stale', 'Stale')], default='active', max_length=32)),
                ('auth_sources', models.JSONField(blank=True, default=list, help_text="e.g. ['AD','Okta','Duo']")),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('stale', 'Stale')], default='active', max_length=32)),
                ('risk_flags', models.JSONField(blank=True, default=list, help_text='Tags like no_mfa, stale_account, etc.')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_of_truth', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=64)),
                ('manager_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='intelligence.identity')),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to='intelligence.team')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ad_group', 'AD Group'), ('okta_group', 'Okta Group'), ('role', 'Role'), ('other', 'Other')], default='other', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('lifecycle_state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('stale', 'Stale')], default='active', max_length=32)),
                ('source_of_truth', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=64)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='intelligence.identity')),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='intelligence.team')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='aws_account, azure_subscription, gcp_project, k8s_cluster, onprem_zone, etc.', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('network_zone', models.CharField(blank=True, default='', max_length=128)),
                ('criticality', models.CharField(choices=[('tier0', 'Tier 0'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('lifecycle_state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('stale', 'Stale')], default='active', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_of_truth', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=64)),
                ('parent_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_environments', to='intelligence.environment')),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='intelligence.team')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('criticality', models.CharField(choices=[('tier0', 'Tier 0'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_services', to='intelligence.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('endpoint', 'Endpoint'), ('server', 'Server'), ('vm', 'Virtual Machine'), ('container', 'Container'), ('database', 'Database'), ('saas_app', 'SaaS App'), ('network_device', 'Network Device'), ('code_repo', 'Code Repo'), ('other', 'Other')], default='other', max_length=32)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('criticality', models.CharField(choices=[('tier0', 'Tier 0'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('regulated', 'Regulated'), ('phi', 'PHI'), ('pii', 'PII'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('lifecycle_state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('stale', 'Stale')], default='active', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_of_truth', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=64)),
                ('business_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='intelligence.businessservice')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='intelligence.environment')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to='intelligence.identity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='intelligence.location')),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='intelligence.team')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('servicenow', 'ServiceNow'), ('flexera', 'Flexera'), ('active_directory', 'Active Directory'), ('okta', 'Okta'), ('duo', 'Duo'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('manual', 'Manual'), ('other', 'Other')], max_length=64)),
                ('record_type', models.CharField(help_text='Class/table/type from source, e.g., cmdb_ci_server', max_length=128)),
                ('external_id', models.CharField(blank=True, default='', max_length=256)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_records', to='intelligence.syncrun')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'record_type'], name='intelligenc_source_2eb35e_idx'), models.Index(fields=['external_id'], name='intelligenc_externa_e304f7_idx'), models.Index(fields=['processed'], name='intelligenc_process_475e32_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['username'], name='intelligenc_usernam_4980a4_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['email'], name='intelligenc_email_95a45d_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['status'], name='intelligenc_status_271494_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('type', 'name')},
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['type'], name='intelligenc_type_18a002_idx'),
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['name'], name='intelligenc_name_59bece_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('type', 'name')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['type'], name='intelligenc_type_cb0550_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name'], name='intelligenc_name_b2df3b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['criticality'], name='intelligenc_critica_53f713_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('type', 'name')},
        ),
    ]
