# Generated by Django 5.1.2 on 2025-11-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Effective', 'Effective'), ('Needs Improvement', 'Needs Improvement'), ('Failing', 'Failing')], default='Effective', max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='controls_co_status_784169_idx')],
                'unique_together': {('org', 'short_description')},
            },
        ),
    ]
