# Generated by Django 5.1.2 on 2025-11-22 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='core.organization'),
        ),
    ]
