# Generated by Django 5.1.2 on 2025-11-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0001_initial'),
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField(blank=True)),
                ('controls', models.ManyToManyField(blank=True, related_name='risks', to='controls.control')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.organization')),
            ],
            options={
                'unique_together': {('org', 'short_description')},
            },
        ),
    ]
